<?xml version="1.0" encoding="UTF-8"?><testsuite errors="1" failures="0" name="Login to Secondtry" skipped="0" tests="1" time="1.57" timestamp="2023-10-05T01:30:14.326064700-05:00[America/Mexico_City]"><testcase name="Second try login"><error type="java.lang.reflect.InvocationTargetException"/><system-err>null&#13;
java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)&#13;
java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)&#13;
java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)&#13;
org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)&#13;
org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)&#13;
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)&#13;
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)&#13;
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)&#13;
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)&#13;
</system-err></testcase></testsuite>